version: "3"

services:
  python:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - .:/app
      - ./static:/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    entrypoint: /app/docker/python/entrypoint.sh
    depends_on:
      - postgres
  postgres:
    image: postgres:15.3-alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  pgdata:
  static: